name: sealingnail
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - open3d
  - tqdm
  - tensorboard
  - h5py
  - scikit-learn
  - pip